### ISSUE TITLE
12 (compress) and 17 (flatten)

### ISSUE THREAD

**Issue by jclymo** [srush/Tensor-Puzzles#12]
Thanks so much for these puzzles, I really enjoyed them. I have a working solution for each one but I'm curious if there are other approaches. In particular: I solved puzzle 12 using puzzle 13, and puzzle 17 I used integer division which creates a deprecation warning. I wondered if you have sample solutions I can compare with, or hints?

**Comment by jaredxfeng** [comment]
I guess not, lol! But I am curious how you solved puzzle 12 with 13!

**Comment by srush** [comment]
If it is helpful, I put up a recent video https://www.youtube.com/watch?v=SiwTAyyvt5s&feature=youtu.be that shows each of the solutions.

**Comment by srush** [comment]
oh sorry! yes I also got the integer division warning.
