### ISSUE TITLE
Chalk diagram pip installing

### ISSUE THREAD

**Issue by Mountagha** [srush/Tensor-Puzzles#19]
The installation of the chalk diagram tool through the github patch seems not to work anymore. Below the issue.

`Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 414.4/414.4 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 622.5/622.5 kB 31.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by DarrenKey** [comment]
It's an issue with a newer version of setuptools; I was able to fix it by adding
`!pip install setuptools==57.5.0` before the first line.
