### ISSUE TITLE
Hints on 10 (roll)

### ISSUE THREAD

**Issue by kshitijsachan** [srush/Tensor-Puzzles#21]
I'm not sure how to solve `roll`. I think I should make a permutation matrix, but I don't know how to make the full permutation matrix in one line? Would appreciate a hint.

**Comment by srush** [comment]
There are two ways to do this. One is to create a permutation matrix as you say. The other is to use advanced indexing, and just use the fact that arr[ind_arr] will work even if ind_arr is a tensor.

**Comment by kshitijsachan** [comment]
Ah advanced indexing, of course! Thanks :)
