### ISSUE TITLE
Problem 18 throwing unexplainable error

### ISSUE THREAD

**Issue by ignasa007** [srush/Tensor-Puzzles#8]
I was working on problem 18 and it is throwing an assertion error when checking the equality between the target and the function output. However, the two tensors seem to be equal. Am I missing something?
<img width="793" alt="Screenshot 2022-07-14 at 4 11 59 AM" src="https://user-images.githubusercontent.com/63924056/178825895-09b867e0-1c82-4caa-9a1b-41d046fe4b18.png">

**Comment by srush** [comment]
Should now be fixed on reload.
